import type { Metadata } from "next";
import {  Geist_Mono, EB_Garamond } from "next/font/google";
import "./globals.css";

import Navbar from "./components/layout/Navbar";
// import Footer from "./components/layout/Footer";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Daniel Fortuné",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${ebGaramond.variable} antialiased dark:bg-resumewhite bg-resumepurple `}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
